server:
  port: 8901

spring:
  application:
    name: CONFIG-SERVER

cloud:
  config:
    server:
      git:
        uri: https://github.com/DivyaIngalagi/config-server.git
        clone-on-start : true